# MySQL configuration
spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/expensedb
    username: root
    password: Nik123@N
# JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
# Email configuration
  mail:
    host: ${BREVO_HOST}
    port: 587
    username: ${BREVO_USER}
    password: ${BREVO_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          from: ${FROM_MAIL}
        protocol: smtp
        properties:
          mail:
            debug: true

server:
  servlet:
    context-path: /api/v0

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

expense:
  tracker:
    frontend:
      url: ${EXPENSE_TRACKER_FRONTEND_URL}

app:
  activation:
    url: ${EXPENSE_TRACKER_BACKEND_URL}